### ISSUE TITLE
Unable to connect a node to connect to prometheus

### ISSUE THREAD

**Issue by y0tsawin** [ticketmaster/googleanalytics_exporter#12]
How do I have to configure a node to connect to prometheus ? 
config prometheus for me 

![2020-06-04_17-17-00](https://user-images.githubusercontent.com/43298144/83745486-cf7b9500-a687-11ea-89e9-c66db02e8a37.jpg)

![2020-06-04_17-18-08](https://user-images.githubusercontent.com/43298144/83745546-e4f0bf00-a687-11ea-956e-1b19499f1ace.jpg)

![2020-06-04_17-18-42](https://user-images.githubusercontent.com/43298144/83745556-ea4e0980-a687-11ea-93ec-c99330eb49f9.jpg)

I want to send the measurement value from this page. Cannot accept this value at this time.

![2020-06-04_17-48-10](https://user-images.githubusercontent.com/43298144/83747946-a0ffb900-a68b-11ea-8a15-ebb47bbc9739.jpg)
Can you recommend me ? I am new to usage.

**Comment by bigkraig** [comment]
That scrape configuration is telling prometheus to scrape its local port 9090 and 9674. There are going to be a few service discovery options in the prometheus documentation if you have a look, but you'll most likely want something that does the kubernetes service discovery based on pod or service labels.

**Comment by y0tsawin** [comment]
Ok i can connect success. My problem is that the dockers are on different networks.
