### ISSUE TITLE
Display index page like other expoterters

### ISSUE THREAD

**Issue by ryanhalliday** [ticketmaster/googleanalytics_exporter#3]
What do you think about adding an index page to match what other exporters do? 

Simply a page to link to `/metrics` so that checking the exporter is running can be `curl localhost:9100` instead of needing `/metrics` too.

Code from official Node Exporter is here: https://github.com/prometheus/node_exporter/blob/55c32fcf02492fe4946f7ab563547cc5df7fc61e/node_exporter.go#L101

Happy to write a pull request if you like the idea?

**Comment by jakesylvestre** [comment]
Fixed in #10
